import { StoreProduct } from '../models/product.model';

export const BASE_PRODUCTS: StoreProduct[] = [
  {
    id: 'p1',
    slug: 'signature-hoodie',
    name: 'Signature Hoodie',
    description: 'Premium cotton blend hoodie with embroidered logo. Comfortable fit for everyday wear.',
    imageUrl: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=600',
    galleryUrls: [
      'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800',
      'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=800'
    ],
    price: 49.99,
    compareAtPrice: 64.99,
    currency: 'USD',
    category: 'Apparel',
    brand: 'House Brand',
    featured: true,
    status: 'active',
    stockQuantity: 24,
    sku: 'HD-001',
    rating: 4.8,
    reviewCount: 24,
    createdAt: '2024-01-15T00:00:00Z',
    variants: [
      { id: 'v1', name: 'S', sku: 'HD-S', price: 49.99, compareAtPrice: 64.99, stockQuantity: 8 },
      { id: 'v2', name: 'M', sku: 'HD-M', price: 49.99, compareAtPrice: 64.99, stockQuantity: 10 },
      { id: 'v3', name: 'L', sku: 'HD-L', price: 49.99, compareAtPrice: 64.99, stockQuantity: 6 }
    ]
  },
  {
    id: 'p2',
    slug: 'ceramic-mug-set',
    name: 'Ceramic Mug Set',
    description: 'Set of two handcrafted ceramic mugs. Dishwasher safe.',
    imageUrl: 'https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?w=600',
    galleryUrls: ['https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?w=800'],
    price: 28.0,
    compareAtPrice: null,
    currency: 'USD',
    category: 'Home',
    brand: 'Artisan Co',
    featured: true,
    status: 'active',
    stockQuantity: 40,
    variants: []
  },
  {
    id: 'p3',
    slug: 'leather-tote',
    name: 'Leather Tote Bag',
    description: 'Full-grain leather tote with interior pockets. Perfect for work or weekend.',
    imageUrl: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600',
    galleryUrls: ['https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800'],
    price: 89.0,
    compareAtPrice: 110.0,
    currency: 'USD',
    category: 'Accessories',
    brand: 'Leather Works',
    featured: true,
    status: 'active',
    stockQuantity: 12,
    variants: []
  },
  {
    id: 'p4',
    slug: 'organic-soap-bar',
    name: 'Organic Soap Bar',
    description: 'Natural ingredients, gentle on skin. Lavender scent.',
    imageUrl: 'https://images.unsplash.com/photo-1600856209923-34372e319a1d?w=600',
    galleryUrls: [],
    price: 8.5,
    currency: 'USD',
    category: 'Wellness',
    brand: 'Pure Botanicals',
    featured: false,
    status: 'active',
    stockQuantity: 100,
    variants: []
  },
  {
    id: 'p5',
    slug: 'wireless-earbuds',
    name: 'Wireless Earbuds',
    description: 'Noise-cancelling earbuds with 24h battery case.',
    imageUrl: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600',
    galleryUrls: [],
    price: 79.99,
    compareAtPrice: 99.99,
    currency: 'USD',
    category: 'Electronics',
    brand: 'SoundWave',
    featured: true,
    status: 'active',
    stockQuantity: 30,
    sku: 'WE-001',
    rating: 4.6,
    reviewCount: 18,
    variants: []
  },
  {
    id: 'p6',
    slug: 'scented-candle',
    name: 'Scented Candle',
    description: 'Soy wax candle, 40-hour burn. Cedar & sage.',
    imageUrl: 'https://images.unsplash.com/photo-1602607504337-53299a0a6b8e?w=600',
    galleryUrls: [],
    price: 22.0,
    currency: 'USD',
    category: 'Home',
    brand: 'Artisan Co',
    featured: true,
    status: 'active',
    stockQuantity: 55,
    variants: []
  },
  {
    id: 'p7',
    slug: 'canvas-cap',
    name: 'Canvas Cap',
    description: 'Adjustable strap, embroidered logo.',
    imageUrl: 'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=600',
    galleryUrls: [],
    price: 24.0,
    currency: 'USD',
    category: 'Apparel',
    brand: 'House Brand',
    featured: false,
    status: 'active',
    stockQuantity: 45,
    variants: []
  },
  {
    id: 'p8',
    slug: 'stainless-bottle',
    name: 'Stainless Steel Bottle',
    description: 'Insulated 32oz bottle. Keeps drinks cold 24h.',
    imageUrl: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600',
    galleryUrls: [],
    price: 34.99,
    currency: 'USD',
    category: 'Accessories',
    brand: 'HydroLife',
    featured: false,
    status: 'active',
    stockQuantity: 60,
    variants: []
  }
];

